# Generated by Django 4.2.2 on 2023-09-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="usercr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstnm", models.CharField(max_length=200, null=True)),
                ("lastnm", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("userid", models.CharField(max_length=200, null=True)),
                ("passwd", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
